FileVersion = 1

[Project]
Name = "Dxc-Beef"
TargetType = "BeefLib"
StartupObject = "Dxc_Beef.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/dist/lib/dxcompiler.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/bin/*.dll\")"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/dist/lib/dxcompiler.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/bin/*.dll\")"]
